name: Retail Pricing ETL

on:
  schedule:
    # Every 12 hours (UTC): 00:00 and 12:00 UTC
    - cron: "0 */12 * * *"
  workflow_dispatch: {}  # allow manual runs

permissions:
  contents: read

jobs:
  etl:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    concurrency:
      group: retail-pricing-etl
      cancel-in-progress: false

    env:
      # Secrets set in: Repo → Settings → Secrets and variables → Actions
      AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
      CONSUMER_ID: ${{ secrets.CONSUMER_ID }}
      WALMART_KEY: ${{ secrets.KEY_VERSION }}
      WALMART_SECRET: ${{ secrets.PRIVATE_KEY_PEM }}
      EBAY_CLIENT_ID: ${{ secrets.EBAY_CLIENT_ID }}
      EBAY_CLIENT_SECRET: ${{ secrets.EBAY_CLIENT_SECRET }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Optional: quick sanity check that critical env vars are present
      - name: Sanity check secrets
        run: |
          python - << 'PY'
          import os, sys
          for k in [
            "AZURE_STORAGE_CONNECTION_STRING",
            "CONSUMER_ID","KEY_VERSION","WALMART_SECRET",
            "EBAY_CLIENT_ID","EBAY_CLIENT_SECRET"
          ]:
              if not os.getenv(k):
                  print(f"Missing secret: {k}")
                  sys.exit(1)
          print("All required secrets present.")
          PY

      - name: Run ETL
        run: |
          python etl_script.py

